Run openssl gost output less strict
With old podman versions, the output of `openssl gost` command is:
```
podman exec 9e /bin/sh -c 'openssl gost /dev/null'
gost is not a known digest
Error: non zero exit code: 1: OCI runtime error
```
instead of just
```
podman exec 9e /bin/sh -c 'openssl gost /dev/null'
gost is not a known digest
```
with newer podman versions.

So, it contains some additional text, and the assertion fails
because we are only expecting "gost is not a known digest".
By doing it as I'm proposing, we cover both cases.